sudo: required
services:
  - docker

before_install:
  - docker build -t davidhospodka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true davidhospodka/react-test npm test -- --coverage

after_success:
  - docker build -t hospicz/multi-client ./client
  - docker build -t hospicz/multi-server ./server
  - docker build -t hospicz/multi-worker ./worker
  - docker build -t hospicz/multi-nginx ./nginx
  #Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hospicz/multi-client
  - docker push hospicz/multi-server
  - docker push hospicz/multi-worker
  - docker push hospicz/multi-nginx
  
  deploy:
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  provider: elasticbeanstalk
  bucket_name: "elasticbeanstalk-eu-west-1-289546914006"
  bucket_path: "docker-multi"
  on:
    branches: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY